//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumingWS.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebServiceResponse", Namespace="http://prueba-ws/")]
    [System.SerializableAttribute()]
    public partial class WebServiceResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://prueba-ws/", ConfigurationName="ServiceReference1.WebServiceSampleSoap")]
    public interface WebServiceSampleSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento name del espacio de nombres http://prueba-ws/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://prueba-ws/HelloWorld", ReplyAction="*")]
        ConsumingWS.ServiceReference1.HelloWorldResponse HelloWorld(ConsumingWS.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://prueba-ws/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumingWS.ServiceReference1.HelloWorldResponse> HelloWorldAsync(ConsumingWS.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento operation del espacio de nombres http://prueba-ws/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://prueba-ws/Calculator", ReplyAction="*")]
        ConsumingWS.ServiceReference1.CalculatorResponse Calculator(ConsumingWS.ServiceReference1.CalculatorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://prueba-ws/Calculator", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumingWS.ServiceReference1.CalculatorResponse> CalculatorAsync(ConsumingWS.ServiceReference1.CalculatorRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://prueba-ws/", Order=0)]
        public ConsumingWS.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ConsumingWS.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://prueba-ws/")]
    public partial class HelloWorldRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string last_name;
        
        public HelloWorldRequestBody() {
        }
        
        public HelloWorldRequestBody(string name, string last_name) {
            this.name = name;
            this.last_name = last_name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://prueba-ws/", Order=0)]
        public ConsumingWS.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ConsumingWS.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://prueba-ws/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculatorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Calculator", Namespace="http://prueba-ws/", Order=0)]
        public ConsumingWS.ServiceReference1.CalculatorRequestBody Body;
        
        public CalculatorRequest() {
        }
        
        public CalculatorRequest(ConsumingWS.ServiceReference1.CalculatorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://prueba-ws/")]
    public partial class CalculatorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int first_value;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int second_value;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string operation;
        
        public CalculatorRequestBody() {
        }
        
        public CalculatorRequestBody(int first_value, int second_value, string operation) {
            this.first_value = first_value;
            this.second_value = second_value;
            this.operation = operation;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculatorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalculatorResponse", Namespace="http://prueba-ws/", Order=0)]
        public ConsumingWS.ServiceReference1.CalculatorResponseBody Body;
        
        public CalculatorResponse() {
        }
        
        public CalculatorResponse(ConsumingWS.ServiceReference1.CalculatorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://prueba-ws/")]
    public partial class CalculatorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsumingWS.ServiceReference1.WebServiceResponse CalculatorResult;
        
        public CalculatorResponseBody() {
        }
        
        public CalculatorResponseBody(ConsumingWS.ServiceReference1.WebServiceResponse CalculatorResult) {
            this.CalculatorResult = CalculatorResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSampleSoapChannel : ConsumingWS.ServiceReference1.WebServiceSampleSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSampleSoapClient : System.ServiceModel.ClientBase<ConsumingWS.ServiceReference1.WebServiceSampleSoap>, ConsumingWS.ServiceReference1.WebServiceSampleSoap {
        
        public WebServiceSampleSoapClient() {
        }
        
        public WebServiceSampleSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSampleSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSampleSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSampleSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumingWS.ServiceReference1.HelloWorldResponse ConsumingWS.ServiceReference1.WebServiceSampleSoap.HelloWorld(ConsumingWS.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld(string name, string last_name) {
            ConsumingWS.ServiceReference1.HelloWorldRequest inValue = new ConsumingWS.ServiceReference1.HelloWorldRequest();
            inValue.Body = new ConsumingWS.ServiceReference1.HelloWorldRequestBody();
            inValue.Body.name = name;
            inValue.Body.last_name = last_name;
            ConsumingWS.ServiceReference1.HelloWorldResponse retVal = ((ConsumingWS.ServiceReference1.WebServiceSampleSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumingWS.ServiceReference1.HelloWorldResponse> ConsumingWS.ServiceReference1.WebServiceSampleSoap.HelloWorldAsync(ConsumingWS.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumingWS.ServiceReference1.HelloWorldResponse> HelloWorldAsync(string name, string last_name) {
            ConsumingWS.ServiceReference1.HelloWorldRequest inValue = new ConsumingWS.ServiceReference1.HelloWorldRequest();
            inValue.Body = new ConsumingWS.ServiceReference1.HelloWorldRequestBody();
            inValue.Body.name = name;
            inValue.Body.last_name = last_name;
            return ((ConsumingWS.ServiceReference1.WebServiceSampleSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumingWS.ServiceReference1.CalculatorResponse ConsumingWS.ServiceReference1.WebServiceSampleSoap.Calculator(ConsumingWS.ServiceReference1.CalculatorRequest request) {
            return base.Channel.Calculator(request);
        }
        
        public ConsumingWS.ServiceReference1.WebServiceResponse Calculator(int first_value, int second_value, string operation) {
            ConsumingWS.ServiceReference1.CalculatorRequest inValue = new ConsumingWS.ServiceReference1.CalculatorRequest();
            inValue.Body = new ConsumingWS.ServiceReference1.CalculatorRequestBody();
            inValue.Body.first_value = first_value;
            inValue.Body.second_value = second_value;
            inValue.Body.operation = operation;
            ConsumingWS.ServiceReference1.CalculatorResponse retVal = ((ConsumingWS.ServiceReference1.WebServiceSampleSoap)(this)).Calculator(inValue);
            return retVal.Body.CalculatorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumingWS.ServiceReference1.CalculatorResponse> ConsumingWS.ServiceReference1.WebServiceSampleSoap.CalculatorAsync(ConsumingWS.ServiceReference1.CalculatorRequest request) {
            return base.Channel.CalculatorAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumingWS.ServiceReference1.CalculatorResponse> CalculatorAsync(int first_value, int second_value, string operation) {
            ConsumingWS.ServiceReference1.CalculatorRequest inValue = new ConsumingWS.ServiceReference1.CalculatorRequest();
            inValue.Body = new ConsumingWS.ServiceReference1.CalculatorRequestBody();
            inValue.Body.first_value = first_value;
            inValue.Body.second_value = second_value;
            inValue.Body.operation = operation;
            return ((ConsumingWS.ServiceReference1.WebServiceSampleSoap)(this)).CalculatorAsync(inValue);
        }
    }
}
